### ISSUE TITLE
mobile view: navbar doesn't close when click on a navlink

### ISSUE THREAD

**Issue by shiivamtaneja** [benlhachemi/modifio#8]
![modifio nav issue](https://github.com/benlhachemi/modifio/assets/79853285/46535322-984b-456c-a769-a75e448c88bd)

The navbar does not automatically disappear when you click on a nav link, as the gif above illustrates.
I would like to contribute to fix this and make a PR.

**Comment by benlhachemi** [comment]
hello @shiivamtaneja,
you are welcome to contribute to fix this issue, just send a pull request
Thanks :)
